Terminate action
AtomicJar/testcontainers-cloud-setup-action pull request #6
Opened 2023-04-21 16:52 UTC by lanwen

2023-04-21 16:54 UTC, eddumelendez approved these changes
LGTM

2023-04-24 06:43 UTC, ilopezluna requested changes
I guess "test with defaults" should include `version=next`
Otherwise we can not test versions released but not published. In this case for example it try to define `--terminate` in the latest (not next) version. So the flag doesn't exists.

2023-04-24 07:34 UTC, lanwen commented
@ilopezluna action should point to the current version in a stable state, but I'll also add the next version case. The current state shouldn't break, otherwise, we can break CI for users of the action, so the test was legit. I'll release the client once signed and restart tests of the action

2023-04-24 07:49 UTC, ilopezluna approved these changes

2023-07-11 10:02 UTC, lanwen commented on README.md
> +- `action` (_optional_): `prepare` (default) / `terminate` - action could be specified explicitly to terminate sessions eagerly
```suggestion
- `action` (_optional_): `prepare` (default) / `terminate` - action could be specified explicitly to terminate sessions eagerly.
```

2023-07-11 10:06 UTC, merged